name: 'Build HDF5'
description: 'Build HDF5 from source'
inputs:
  ref:
    description: "Branch/tag/sha of HDF5 to checkout"
    required: true
    default: hdf5-1_12_2
  hdf5-dir:
    required: true
    description: "Directory to install into"
    default: "/opt/hdf5"
outputs:
  hdf5-dir:
    description: "Directory where HDF5 is installed"
    value: ${{ inputs.hdf5-dir }}
runs:
  using: composite
  steps:
    - name: Cache Build
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.hdf5-dir }}
        key: ${{ runner.os }}-cache-hdf5-${{ inputs.ref }}
    - id: checkout
      name: Checkout
      uses: actions/checkout@v3
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      with:
        repository: 'HDFGroup/hdf5'
        ref: ${{ inputs.ref }}
        path: 'hdf5-build'
    - id: build
      name: Build HDF5
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: HDF5_DIR="${{ inputs.hdf5-dir }}" ./build.sh
