name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        arch: [x64]
        experimental: [false]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - id: run
        name: Run Action
        uses: ./  # run this action
        with:
          hdf5-dir: "${{ github.workspace }}/my-hdf5"
      - name: test
        shell: bash
        run: HDF5_DIR='${{ steps.run.outputs.hdf5-dir }}' ./test.sh
